export const calvin = [
  {
    id: 1,
    marca: "Calvin",
    talle: "XL",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 2,
    marca: "Calvin",
    talle: "XL",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 9000,
    codigo: "ABC123",
  },
  {
    id: 3,
    marca: "Calvin",
    talle: "XL",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "ABC123",
  },
  {
    id: 4,
    marca: "Calvin",
    talle: "XL",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "ABC123",
  },
];
