export const columbia = [
  // {
  //   id: 1,
  //   marca: "Columbia",
  //   talle: "XL",
  //   imagen: "",
  //   imagen2: "",
  //   Cantidad: "",
  //   precio: 8000,
  //   codigo: "ABC123",
  // },
  // {
  //   id: 2,
  //   marca: "Columbia",
  //   talle: "L",
  //   imagen: "",
  //   imagen2: "",
  //   Cantidad: "",
  //   precio: 7500,
  //   codigo: "DEF456",
  // },
  // {
  //   id: 3,
  //   marca: "Columbia",
  //   talle: "M",
  //   imagen: "",
  //   imagen2: "",
  //   Cantidad: "",
  //   precio: 7000,
  //   codigo: "GHI789",
  // },
  // {
  //   id: 4,
  //   marca: "Columbia",
  //   talle: "M",
  //   imagen: "",
  //   imagen2: "",
  //   Cantidad: "",
  //   precio: 7000,
  //   codigo: "GHI789",
  // },
  // {
  //   id: 5,
  //   marca: "Columbia",
  //   talle: "M",
  //   imagen: "",
  //   imagen2: "",
  //   Cantidad: "",
  //   precio: 7000,
  //   codigo: "GHI789",
  // },
  // {
  //   id: 6,
  //   marca: "Columbia",
  //   talle: "M",
  //   imagen: "",
  //   imagen2: "",
  //   Cantidad: "",
  //   precio: 7000,
  //   codigo: "GHI789",
  // },
  // {
  //   id: 7,
  //   marca: "Columbia",
  //   talle: "M",
  //   imagen: "",
  //   imagen2: "",
  //   Cantidad: "",
  //   precio: 7000,
  //   codigo: "GHI789",
  // },
  // {
  //   id: 8,
  //   marca: "Columbia",
  //   talle: "M",
  //   imagen: "",
  //   imagen2: "",
  //   Cantidad: "",
  //   precio: 7000,
  //   codigo: "GHI789",
  // },
  // {
  //   id: 9,
  //   marca: "Columbia",
  //   talle: "M",
  //   imagen: "",
  //   imagen2: "",
  //   Cantidad: "",
  //   precio: 7000,
  //   codigo: "GHI789",
  // },
  // {
  //   id: 10,
  //   marca: "Columbia",
  //   talle: "M",
  //   imagen: "",
  //   imagen2: "",
  //   Cantidad: "",
  //   precio: 7000,
  //   codigo: "GHI789",
  // },
  // {
  //   id: 11,
  //   marca: "Columbia",
  //   talle: "M",
  //   imagen: "",
  //   imagen2: "",
  //   Cantidad: "",
  //   precio: 7000,
  //   codigo: "GHI789",
  // },
];
