export const jordan = [
  {
    id: 1,
    marca: "Jordan",
    talle: "XL",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 2,
    marca: "Jordan",
    talle: "L",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7500,
    codigo: "DEF456",
  },
  {
    id: 3,
    marca: "Jordan",
    talle: "M",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "GHI789",
  },
  {
    id: 4,
    marca: "Jordan",
    talle: "M",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "GHI789",
  },
  {
    id: 5,
    marca: "Jordan",
    talle: "M",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "GHI789",
  },
  {
    id: 6,
    marca: "Jordan",
    talle: "M",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "GHI789",
  },
  {
    id: 7,
    marca: "Jordan",
    talle: "M",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "GHI789",
  },
  {
    id: 8,
    marca: "Jordan",
    talle: "M",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "GHI789",
  },
];
