import jordan1 from "../assets/img/jordan/dorso.jpg";
import jordan from "../assets/img/jordan/frente.jpg";

export const nike = [
  {
    id: 1,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 2,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 3,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 4,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 5,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 6,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 7,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 8,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 9,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 10,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 11,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 12,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 13,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 14,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 15,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 16,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 17,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 18,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 19,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 20,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 21,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 22,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 23,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 24,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 25,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 26,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 27,
    marca: "Nike",
    talle: "XL",
    imagen: jordan,
    imagen2: jordan1,
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
];
