export const reebok = [
  {
    id: 1,
    marca: "Reebok",
    talle: "XL",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 8000,
    codigo: "ABC123",
  },
  {
    id: 2,
    marca: "Reebok",
    talle: "L",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7500,
    codigo: "DEF456",
  },
  {
    id: 3,
    marca: "Reebok",
    talle: "M",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "GHI789",
  },
  {
    id: 4,
    marca: "Reebok",
    talle: "M",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "GHI789",
  },
  {
    id: 5,
    marca: "Reebok",
    talle: "M",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "GHI789",
  },
  {
    id: 6,
    marca: "Reebok",
    talle: "M",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "GHI789",
  },
  {
    id: 7,
    marca: "Reebok",
    talle: "M",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "GHI789",
  },
  {
    id: 8,
    marca: "Reebok",
    talle: "M",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "GHI789",
  },
  {
    id: 9,
    marca: "Reebok",
    talle: "M",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "GHI789",
  },
  {
    id: 10,
    marca: "Reebok",
    talle: "M",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "GHI789",
  },
  {
    id: 11,
    marca: "Reebok",
    talle: "M",
    imagen: "",
    imagen2: "",
    Cantidad: "",
    precio: 7000,
    codigo: "GHI789",
  },
];
